linters-settings:
  cyclop:
    package-average: 5.0
  funlen:
    lines: 100
    statements: 50
  gci:
    local-prefixes: github.com/willbeason/wikipedia
  gocognit:
    min-complexity: 10
  goconst:
    numbers: true
    min-len: 4
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 10
  gofumpt:
    lang-version: "1.17"
  goimports:
    local-prefixes: github.com/willbeason/wikipedia
  gosimple:
    go: "1.17"
  govet:
    check-shadowing: true
  lll:
    line-length: 150
  misspell:
    locale: US
  gomnd:
    settings:
      mnd:
        ignored-functions: mainCmd
  staticcheck:
    go: "1.17"
  stylecheck:
    go: "1.17"
  unused:
    go: "1.17"

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      text: "varnamelen"

linters:
  enable-all: true
  disable:
   - golint
   - exhaustivestruct
   - interfacer
   - maligned
   - scopelint
   - structcheck
   - ifshort
   - varcheck
   - nosnakecase
   - deadcode
   # To re-enable
   - varnamelen
   - wrapcheck
   - paralleltest
   - forbidigo
   - gocognit
   - gomnd
   - gochecknoglobals
   - exhaustruct
   - funlen
   - gocyclo
   - cyclop
   - maintidx
   - ireturn
   - lll
   - prealloc
   - unused
   - gocritic
   - gosec
   - makezero
   - unparam
   - wsl
   - contextcheck
   - forcetypeassert
   - ineffassign
   - nlreturn
   - errorlint
   - goerr113
   - staticcheck
   - tagliatelle
   - testpackage
   - nonamedreturns