linters-settings:
  mnd:
    ignored-numbers:
      - '2'
      - '2.0'
      - '3'
      - '3.0'
      - '10'
      - '10.0'
      - '100'
    ignored-functions:
      - cobra.ExactArgs
  wrapcheck:
    ignorePackageGlobs:
      - github.com/willbeason/wikipedia/*
      - context

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - lll
        - maintidx

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - copyloopvar
#    - cyclop # Too many instances to deal with now.
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - fatcontext
    - gci
    - gocheckcompilerdirectives
#    - gochecknoglobals # Need to implement configuration files to do this properly.
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofumpt
    - inamedparam
    - interfacebloat
    - intrange
#    - lll
    - maintidx
    - makezero
    - mirror
#    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
#    - nolintlint
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck