linters-settings:
  cyclop:
    package-average: 5.0
  funlen:
    lines: 100
    statements: 50
  gci:
    local-prefixes: github.com/willbeason/wikipedia
  gocognit:
    min-complexity: 10
  goconst:
    numbers: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 10
  gofumpt:
    lang-version: "1.17"
  goimports:
    local-prefixes: github.com/willbeason/wikipedia
  gosimple:
    go: "1.17"
  govet:
    check-shadowing: true
  lll:
    line-length: 150
  misspell:
    locale: US
  staticcheck:
    go: "1.17"
  stylecheck:
    go: "1.17"
  unused:
    go: "1.17"

linters:
  enable-all: true
  disable:
   - golint
   - interfacer
   - maligned
   - scopelint
