linters-settings:
  cyclop:
    package-average: 5.0
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 10
  goconst:
    numbers: true
    min-len: 4
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 10
  goimports:
    local-prefixes: github.com/willbeason/wikipedia
  govet:
    shadow: true
  lll:
    line-length: 150
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      text: "varnamelen"

linters:
  enable-all: true
  disable:
   - execinquery
   # To re-enable
   - varnamelen
   - wrapcheck
   - paralleltest
   - forbidigo
   - gocognit
   - gomnd
   - gochecknoglobals
   - exhaustruct
   - funlen
   - gocyclo
   - cyclop
   - maintidx
   - ireturn
   - lll
   - prealloc
   - unused
   - gocritic
   - gosec
   - makezero
   - unparam
   - wsl
   - contextcheck
   - forcetypeassert
   - ineffassign
   - nlreturn
   - errorlint
   - err113
   - staticcheck
   - tagliatelle
   - testpackage
   - nonamedreturns