linters-settings:
  mnd:
    ignored-numbers:
      - '2'
      - '2.0'
      - '3'
      - '3.0'
      - '10'
      - '10.0'
      - '100'
  wrapcheck:
    ignorePackageGlobs:
      - github.com/willbeason/wikipedia/*
      - context

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - lll

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - copyloopvar
#    - cyclop
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - fatcontext
    - gci
    - gocheckcompilerdirectives
#    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
#    - gocognit
    - goconst
#    - gocritic
#    - gocyclo
    - godot
    - godox
    - gofumpt
    - inamedparam
    - interfacebloat
    - intrange
#    - ireturn
    - lll
#    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck