// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: pkg/ordinality/ordinality.proto

package ordinality

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PageWordBag is an unordered count of all words in the document which are present in some
// dictionary.
type PageWordBag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id is the unique identifier of the page.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Title is the textual title of the page.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Words is the bag of words contained in the page.
	Words []*WordCount `protobuf:"bytes,3,rep,name=words,proto3" json:"words,omitempty"`
}

func (x *PageWordBag) Reset() {
	*x = PageWordBag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ordinality_ordinality_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageWordBag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageWordBag) ProtoMessage() {}

func (x *PageWordBag) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ordinality_ordinality_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageWordBag.ProtoReflect.Descriptor instead.
func (*PageWordBag) Descriptor() ([]byte, []int) {
	return file_pkg_ordinality_ordinality_proto_rawDescGZIP(), []int{0}
}

func (x *PageWordBag) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PageWordBag) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PageWordBag) GetWords() []*WordCount {
	if x != nil {
		return x.Words
	}
	return nil
}

// WordCount is a word, noted by its unique identifier, and the number of times it appears in the
// page.
type WordCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word  uint32 `protobuf:"varint,1,opt,name=word,proto3" json:"word,omitempty"`
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *WordCount) Reset() {
	*x = WordCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ordinality_ordinality_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordCount) ProtoMessage() {}

func (x *WordCount) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ordinality_ordinality_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordCount.ProtoReflect.Descriptor instead.
func (*WordCount) Descriptor() ([]byte, []int) {
	return file_pkg_ordinality_ordinality_proto_rawDescGZIP(), []int{1}
}

func (x *WordCount) GetWord() uint32 {
	if x != nil {
		return x.Word
	}
	return 0
}

func (x *WordCount) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_pkg_ordinality_ordinality_proto protoreflect.FileDescriptor

var file_pkg_ordinality_ordinality_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x74, 0x79,
	0x2f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x60, 0x0a,
	0x0b, 0x50, 0x61, 0x67, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x42, 0x61, 0x67, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x2e, 0x57,
	0x6f, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x22,
	0x35, 0x0a, 0x09, 0x57, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_ordinality_ordinality_proto_rawDescOnce sync.Once
	file_pkg_ordinality_ordinality_proto_rawDescData = file_pkg_ordinality_ordinality_proto_rawDesc
)

func file_pkg_ordinality_ordinality_proto_rawDescGZIP() []byte {
	file_pkg_ordinality_ordinality_proto_rawDescOnce.Do(func() {
		file_pkg_ordinality_ordinality_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_ordinality_ordinality_proto_rawDescData)
	})
	return file_pkg_ordinality_ordinality_proto_rawDescData
}

var file_pkg_ordinality_ordinality_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_ordinality_ordinality_proto_goTypes = []interface{}{
	(*PageWordBag)(nil), // 0: ordinality.PageWordBag
	(*WordCount)(nil),   // 1: ordinality.WordCount
}
var file_pkg_ordinality_ordinality_proto_depIdxs = []int32{
	1, // 0: ordinality.PageWordBag.words:type_name -> ordinality.WordCount
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_ordinality_ordinality_proto_init() }
func file_pkg_ordinality_ordinality_proto_init() {
	if File_pkg_ordinality_ordinality_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_ordinality_ordinality_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageWordBag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ordinality_ordinality_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_ordinality_ordinality_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_ordinality_ordinality_proto_goTypes,
		DependencyIndexes: file_pkg_ordinality_ordinality_proto_depIdxs,
		MessageInfos:      file_pkg_ordinality_ordinality_proto_msgTypes,
	}.Build()
	File_pkg_ordinality_ordinality_proto = out.File
	file_pkg_ordinality_ordinality_proto_rawDesc = nil
	file_pkg_ordinality_ordinality_proto_goTypes = nil
	file_pkg_ordinality_ordinality_proto_depIdxs = nil
}
