// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: pkg/classify/classify.proto

package classify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Classification int32

const (
	Classification_UNKNOWN                   Classification = 0
	Classification_PHILOSOPHY                Classification = 1
	Classification_PSYCHOLOGY                Classification = 2
	Classification_RELIGION                  Classification = 3
	Classification_HISTORY                   Classification = 4
	Classification_GEOGRAPHY                 Classification = 5
	Classification_SOCIAL_SCIENCES           Classification = 6
	Classification_POLITICAL_SCIENCE         Classification = 7
	Classification_LAW                       Classification = 8
	Classification_EDUCATION                 Classification = 9
	Classification_MUSIC                     Classification = 10
	Classification_FINE_ARTS                 Classification = 11
	Classification_PHILOLOGY_AND_LINGUISTICS Classification = 12
	Classification_LITERATURE                Classification = 13
	Classification_SCIENCE                   Classification = 14
	Classification_MEDICINE                  Classification = 15
	Classification_AGRICULTURE               Classification = 16
	Classification_TECHNOLOGY                Classification = 17
	Classification_MILITARY_SCIENCE          Classification = 18
	Classification_INFORMATION_SCIENCE       Classification = 19
)

// Enum value maps for Classification.
var (
	Classification_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "PHILOSOPHY",
		2:  "PSYCHOLOGY",
		3:  "RELIGION",
		4:  "HISTORY",
		5:  "GEOGRAPHY",
		6:  "SOCIAL_SCIENCES",
		7:  "POLITICAL_SCIENCE",
		8:  "LAW",
		9:  "EDUCATION",
		10: "MUSIC",
		11: "FINE_ARTS",
		12: "PHILOLOGY_AND_LINGUISTICS",
		13: "LITERATURE",
		14: "SCIENCE",
		15: "MEDICINE",
		16: "AGRICULTURE",
		17: "TECHNOLOGY",
		18: "MILITARY_SCIENCE",
		19: "INFORMATION_SCIENCE",
	}
	Classification_value = map[string]int32{
		"UNKNOWN":                   0,
		"PHILOSOPHY":                1,
		"PSYCHOLOGY":                2,
		"RELIGION":                  3,
		"HISTORY":                   4,
		"GEOGRAPHY":                 5,
		"SOCIAL_SCIENCES":           6,
		"POLITICAL_SCIENCE":         7,
		"LAW":                       8,
		"EDUCATION":                 9,
		"MUSIC":                     10,
		"FINE_ARTS":                 11,
		"PHILOLOGY_AND_LINGUISTICS": 12,
		"LITERATURE":                13,
		"SCIENCE":                   14,
		"MEDICINE":                  15,
		"AGRICULTURE":               16,
		"TECHNOLOGY":                17,
		"MILITARY_SCIENCE":          18,
		"INFORMATION_SCIENCE":       19,
	}
)

func (x Classification) Enum() *Classification {
	p := new(Classification)
	*p = x
	return p
}

func (x Classification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Classification) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_classify_classify_proto_enumTypes[0].Descriptor()
}

func (Classification) Type() protoreflect.EnumType {
	return &file_pkg_classify_classify_proto_enumTypes[0]
}

func (x Classification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Classification.Descriptor instead.
func (Classification) EnumDescriptor() ([]byte, []int) {
	return file_pkg_classify_classify_proto_rawDescGZIP(), []int{0}
}

// ClassifiedArticles is a map from article IDs to their Classification.
type ClassifiedArticles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Articles map[uint32]Classification `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=Classification"`
}

func (x *ClassifiedArticles) Reset() {
	*x = ClassifiedArticles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_classify_classify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifiedArticles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifiedArticles) ProtoMessage() {}

func (x *ClassifiedArticles) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_classify_classify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifiedArticles.ProtoReflect.Descriptor instead.
func (*ClassifiedArticles) Descriptor() ([]byte, []int) {
	return file_pkg_classify_classify_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifiedArticles) GetArticles() map[uint32]Classification {
	if x != nil {
		return x.Articles
	}
	return nil
}

type ClassifiedIDs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pages map[uint32]Classification `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=Classification"`
}

func (x *ClassifiedIDs) Reset() {
	*x = ClassifiedIDs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_classify_classify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifiedIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifiedIDs) ProtoMessage() {}

func (x *ClassifiedIDs) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_classify_classify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifiedIDs.ProtoReflect.Descriptor instead.
func (*ClassifiedIDs) Descriptor() ([]byte, []int) {
	return file_pkg_classify_classify_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifiedIDs) GetPages() map[uint32]Classification {
	if x != nil {
		return x.Pages
	}
	return nil
}

type ClassifiedTitles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pages map[string]Classification `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=Classification"`
}

func (x *ClassifiedTitles) Reset() {
	*x = ClassifiedTitles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_classify_classify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifiedTitles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifiedTitles) ProtoMessage() {}

func (x *ClassifiedTitles) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_classify_classify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifiedTitles.ProtoReflect.Descriptor instead.
func (*ClassifiedTitles) Descriptor() ([]byte, []int) {
	return file_pkg_classify_classify_proto_rawDescGZIP(), []int{2}
}

func (x *ClassifiedTitles) GetPages() map[string]Classification {
	if x != nil {
		return x.Pages
	}
	return nil
}

type PageClassificationsMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pages map[uint32]*PageClassifications `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PageClassificationsMap) Reset() {
	*x = PageClassificationsMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_classify_classify_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageClassificationsMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageClassificationsMap) ProtoMessage() {}

func (x *PageClassificationsMap) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_classify_classify_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageClassificationsMap.ProtoReflect.Descriptor instead.
func (*PageClassificationsMap) Descriptor() ([]byte, []int) {
	return file_pkg_classify_classify_proto_rawDescGZIP(), []int{3}
}

func (x *PageClassificationsMap) GetPages() map[uint32]*PageClassifications {
	if x != nil {
		return x.Pages
	}
	return nil
}

type PageClassifications struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Classifications []Classification `protobuf:"varint,1,rep,packed,name=classifications,proto3,enum=Classification" json:"classifications,omitempty"`
}

func (x *PageClassifications) Reset() {
	*x = PageClassifications{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_classify_classify_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageClassifications) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageClassifications) ProtoMessage() {}

func (x *PageClassifications) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_classify_classify_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageClassifications.ProtoReflect.Descriptor instead.
func (*PageClassifications) Descriptor() ([]byte, []int) {
	return file_pkg_classify_classify_proto_rawDescGZIP(), []int{4}
}

func (x *PageClassifications) GetClassifications() []Classification {
	if x != nil {
		return x.Classifications
	}
	return nil
}

var File_pkg_classify_classify_proto protoreflect.FileDescriptor

var file_pkg_classify_classify_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x2f, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x01,
	0x0a, 0x12, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x64, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x08, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x2e, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x73, 0x1a, 0x4c, 0x0a, 0x0d, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x8b, 0x01, 0x0a, 0x0d, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x49, 0x44, 0x73, 0x12, 0x2f, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x64, 0x49,
	0x44, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x70,
	0x61, 0x67, 0x65, 0x73, 0x1a, 0x49, 0x0a, 0x0a, 0x50, 0x61, 0x67, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x91, 0x01, 0x0a, 0x10, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x64, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x49, 0x0a, 0x0a, 0x50, 0x61, 0x67, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0xa2, 0x01, 0x0a, 0x16, 0x50, 0x61, 0x67, 0x65, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4d, 0x61, 0x70, 0x12, 0x38,
	0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x50, 0x61, 0x67, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x4d, 0x61, 0x70, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x4e, 0x0a, 0x0a, 0x50, 0x61, 0x67, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x50, 0x0a, 0x13, 0x50, 0x61, 0x67, 0x65,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x39, 0x0a, 0x0f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2a, 0xdf, 0x02, 0x0a, 0x0e, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x48,
	0x49, 0x4c, 0x4f, 0x53, 0x4f, 0x50, 0x48, 0x59, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x53,
	0x59, 0x43, 0x48, 0x4f, 0x4c, 0x4f, 0x47, 0x59, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45,
	0x4c, 0x49, 0x47, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x48, 0x49, 0x53, 0x54,
	0x4f, 0x52, 0x59, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x47, 0x45, 0x4f, 0x47, 0x52, 0x41, 0x50,
	0x48, 0x59, 0x10, 0x05, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x4f, 0x43, 0x49, 0x41, 0x4c, 0x5f, 0x53,
	0x43, 0x49, 0x45, 0x4e, 0x43, 0x45, 0x53, 0x10, 0x06, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x4f, 0x4c,
	0x49, 0x54, 0x49, 0x43, 0x41, 0x4c, 0x5f, 0x53, 0x43, 0x49, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x07,
	0x12, 0x07, 0x0a, 0x03, 0x4c, 0x41, 0x57, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x44, 0x55,
	0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x09, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x55, 0x53, 0x49,
	0x43, 0x10, 0x0a, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x49, 0x4e, 0x45, 0x5f, 0x41, 0x52, 0x54, 0x53,
	0x10, 0x0b, 0x12, 0x1d, 0x0a, 0x19, 0x50, 0x48, 0x49, 0x4c, 0x4f, 0x4c, 0x4f, 0x47, 0x59, 0x5f,
	0x41, 0x4e, 0x44, 0x5f, 0x4c, 0x49, 0x4e, 0x47, 0x55, 0x49, 0x53, 0x54, 0x49, 0x43, 0x53, 0x10,
	0x0c, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x49, 0x54, 0x45, 0x52, 0x41, 0x54, 0x55, 0x52, 0x45, 0x10,
	0x0d, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x43, 0x49, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x0e, 0x12, 0x0c,
	0x0a, 0x08, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x10, 0x0f, 0x12, 0x0f, 0x0a, 0x0b,
	0x41, 0x47, 0x52, 0x49, 0x43, 0x55, 0x4c, 0x54, 0x55, 0x52, 0x45, 0x10, 0x10, 0x12, 0x0e, 0x0a,
	0x0a, 0x54, 0x45, 0x43, 0x48, 0x4e, 0x4f, 0x4c, 0x4f, 0x47, 0x59, 0x10, 0x11, 0x12, 0x14, 0x0a,
	0x10, 0x4d, 0x49, 0x4c, 0x49, 0x54, 0x41, 0x52, 0x59, 0x5f, 0x53, 0x43, 0x49, 0x45, 0x4e, 0x43,
	0x45, 0x10, 0x12, 0x12, 0x17, 0x0a, 0x13, 0x49, 0x4e, 0x46, 0x4f, 0x52, 0x4d, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x53, 0x43, 0x49, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x13, 0x42, 0x0e, 0x5a, 0x0c,
	0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_classify_classify_proto_rawDescOnce sync.Once
	file_pkg_classify_classify_proto_rawDescData = file_pkg_classify_classify_proto_rawDesc
)

func file_pkg_classify_classify_proto_rawDescGZIP() []byte {
	file_pkg_classify_classify_proto_rawDescOnce.Do(func() {
		file_pkg_classify_classify_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_classify_classify_proto_rawDescData)
	})
	return file_pkg_classify_classify_proto_rawDescData
}

var file_pkg_classify_classify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_classify_classify_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_classify_classify_proto_goTypes = []interface{}{
	(Classification)(0),            // 0: Classification
	(*ClassifiedArticles)(nil),     // 1: ClassifiedArticles
	(*ClassifiedIDs)(nil),          // 2: ClassifiedIDs
	(*ClassifiedTitles)(nil),       // 3: ClassifiedTitles
	(*PageClassificationsMap)(nil), // 4: PageClassificationsMap
	(*PageClassifications)(nil),    // 5: PageClassifications
	nil,                            // 6: ClassifiedArticles.ArticlesEntry
	nil,                            // 7: ClassifiedIDs.PagesEntry
	nil,                            // 8: ClassifiedTitles.PagesEntry
	nil,                            // 9: PageClassificationsMap.PagesEntry
}
var file_pkg_classify_classify_proto_depIdxs = []int32{
	6, // 0: ClassifiedArticles.articles:type_name -> ClassifiedArticles.ArticlesEntry
	7, // 1: ClassifiedIDs.pages:type_name -> ClassifiedIDs.PagesEntry
	8, // 2: ClassifiedTitles.pages:type_name -> ClassifiedTitles.PagesEntry
	9, // 3: PageClassificationsMap.pages:type_name -> PageClassificationsMap.PagesEntry
	0, // 4: PageClassifications.classifications:type_name -> Classification
	0, // 5: ClassifiedArticles.ArticlesEntry.value:type_name -> Classification
	0, // 6: ClassifiedIDs.PagesEntry.value:type_name -> Classification
	0, // 7: ClassifiedTitles.PagesEntry.value:type_name -> Classification
	5, // 8: PageClassificationsMap.PagesEntry.value:type_name -> PageClassifications
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_classify_classify_proto_init() }
func file_pkg_classify_classify_proto_init() {
	if File_pkg_classify_classify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_classify_classify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifiedArticles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_classify_classify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifiedIDs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_classify_classify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifiedTitles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_classify_classify_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageClassificationsMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_classify_classify_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageClassifications); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_classify_classify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_classify_classify_proto_goTypes,
		DependencyIndexes: file_pkg_classify_classify_proto_depIdxs,
		EnumInfos:         file_pkg_classify_classify_proto_enumTypes,
		MessageInfos:      file_pkg_classify_classify_proto_msgTypes,
	}.Build()
	File_pkg_classify_classify_proto = out.File
	file_pkg_classify_classify_proto_rawDesc = nil
	file_pkg_classify_classify_proto_goTypes = nil
	file_pkg_classify_classify_proto_depIdxs = nil
}
