// nolint
package article_test

var NoetherLinks = []string{
	"Mathematician",
	"Abstract algebra",
	"Noether's theorem",
	"Noether's second theorem",
	"Mathematical physics",
	"Pavel Alexandrov",
	"Albert Einstein",
	"Jean Dieudonné",
	"Hermann Weyl",
	"Norbert Wiener",
	"List of women in mathematics",
	"Ring (mathematics)",
	"Field (mathematics)",
	"Algebra over a field",
	"Noether's theorem",
	"Symmetry in physics",
	"Conservation law (physics)",
	"Jewish family",
	"Franconia",
	"Erlangen",
	"Max Noether",
	"University of Erlangen",
	"Paul Gordan",
	"David Hilbert",
	"Felix Klein",
	"University of Göttingen",
	"Habilitation",
	"Privatdozent",
	"Göttingen",
	"Bartel Leendert van der Waerden",
	"Moderne Algebra",
	"International Congress of Mathematicians",
	"Zürich",
	"Anti-Jewish legislation in pre-war Nazi Germany",
	"Bryn Mawr College",
	"Pennsylvania",
	"Marie Johanna Weiss",
	"Olga Taussky-Todd",
	"Institute for Advanced Study",
	"Princeton, New Jersey",
	"Epoch",
	"Algebraic invariant",
	"Field (mathematics)",
	"Calculus of variations",
	"Noether's theorem",
	"Ideal (ring theory)",
	"Commutative ring",
	"Ascending chain condition",
	"Noetherian (disambiguation)",
	"Noncommutative algebra",
	"Hypercomplex number",
	"Representation theory",
	"Group (mathematics)",
	"Module (mathematics)",
	"Algebraic topology",
	"Max Noether",
	"Myopia",
	"Lisp",
	"Chemistry",
	"Fritz Noether",
	"Munich",
	"Applied mathematics",
	"University of Erlangen",
	"Mixed-sex education",
	"Academic audit",
	"Realgymnasium",
	"Nuremberg",
	"University of Göttingen",
	"Karl Schwarzschild",
	"Hermann Minkowski",
	"Otto Blumenthal",
	"Felix Klein",
	"David Hilbert",
	"Paul Gordan",
	"Max Noether",
	"Erhard Schmidt",
	"Ernst Sigismund Fischer",
	"Hermann Weyl",
	"Auguste Dick",
	"David Hilbert",
	"Field (mathematics)",
	"Rational function",
	"Invariant theory",
	"Finite group",
	"Abstract algebra",
	"Braunschweig",
	"Königsberg",
	"University of Giessen",
	"Munich",
	"Felix Klein",
	"Philology",
	"Historian",
	"Privatdozent",
	"Pavel Alexandrov",
	"Socialist democracy",
	"German Army (German Empire)",
	"World War I",
	"Theorem",
	"Noether's theorem",
	"Conservation law (physics)",
	"Symmetry in physics",
	"Felix Klein",
	"Leon M. Lederman",
	"Christopher T. Hill",
	"Modern physics",
	"Pythagorean theorem",
	"German Revolution of 1918–1919",
	"Habilitation",
	"Prussia",
	"Ausserordentlicher Professor",
	"Professor",
	"Abstract algebra",
	"Nathan Jacobson",
	"Ideal theory",
	"Ideal (ring theory)",
	"Ring (mathematics)",
	"Ascending chain condition",
	"Ideal (ring theory)",
	"Lasker-Noether theorem",
	"Irving Kaplansky",
	"Noetherian",
	"Bartel Leendert van der Waerden",
	"Emil Artin",
	"Emil Artin",
	"Richard Brauer",
	"Helmut Hasse",
	"Noncommutative algebra",
	"Pavel Alexandrov",
	"Pavel Urysohn",
	"Princeton University",
	"Rockefeller Foundation",
	"Edmund Landau",
	"Grete Hermann",
	"Quantum mechanics",
	"Ideal theory",
	"Tuberculosis",
	"University of Jena",
	"University of Halle",
	"Humboldt University",
	"Werner Weber (mathematician)",
	"Jakob Levitzki",
	"Yale University",
	"Hebrew University of Jerusalem",
	"Levitzky's theorem",
	"Hopkins–Levitzki theorem",
	"Ring theory",
	"Max Deuring",
	"Hans Fitting",
	"Ernst Witt",
	"Chiungtze C. Tsen",
	"Otto Schilling",
	"Arithmetic geometry",
	"Group theory",
	"Fitting's theorem",
	"Fitting lemma",
	"Gustav Herglotz",
	"Riemann-Roch Theorem",
	"Zeta-function",
	"List of things named after Ernst Witt",
	"Tsen's theorem",
	"China",
	"National Chekiang University",
	"Helmut Hasse",
	"University of Marburg",
	"Post doc",
	"Trinity College, Cambridge",
	"Splitting field",
	"P-adic number",
	"World War II",
	"Wolfgang Krull",
	"Commutative algebra",
	"Krull's principal ideal theorem",
	"Krull dimension",
	"Gottfried Köthe",
	"Hypercomplex number",
	"Nazi Germany",
	"Gottfried E. Noether",
	"Olga Taussky-Todd",
	"Carl Ludwig Siegel",
	"Paul Dubreil",
	"Moscow State University",
	"Pavel Alexandrov",
	"Algebraic geometry",
	"Lev Pontryagin",
	"Nikolai Chebotaryov",
	"Galois theory",
	"Russian Revolution",
	"Soviet Union",
	"Bolshevik",
	"Pension (lodging)",
	"Hermann Weyl",
	"German Revolution of 1918–1919",
	"Social Democratic Party of Germany",
	"Independent Social Democratic Party of Germany",
	"Colin McLarty",
	"Narkompros",
	"Emil Artin",
	"Ackermann–Teubner Memorial Award",
	"Göttingen Academy of Sciences",
	"Ordentlicher Professor",
	"Helmut Hasse",
	"Mathematische Annalen",
	"Noncommutative algebra",
	"Commutative algebra",
	"Quadratic reciprocity",
	"International Congress of Mathematicians",
	"Zürich",
	"Hermann Weyl",
	"Edmund Landau",
	"Wolfgang Krull",
	"Adolf Hitler",
	"Chancellor of Germany (German Reich)",
	"Nazi",
	"Privatdozent",
	"Werner Weber (mathematician)",
	"Antisemitism",
	"Deutsche Mathematik",
	"Law for the Restoration of the Professional Civil Service",
	"Frontkämpferprivileg",
	"Max Born",
	"Richard Courant",
	"Hermann Weyl",
	"Class field theory",
	"Paramilitary",
	"Sturmabteilung",
	"Albert Einstein",
	"Hermann Weyl",
	"Institute for Advanced Study",
	"Princeton, New Jersey",
	"Immigration",
	"Bryn Mawr College",
	"Somerville College",
	"University of Oxford",
	"Rockefeller Foundation",
	"Anna Johnson Pell Wheeler",
	"Marion Edwards Park",
	"Marie Johanna Weiss",
	"Olga Taussky-Todd",
	"Van der Waerden",
	"Erich Hecke",
	"Richard Brauer",
	"Normal extension",
	"Abraham Flexner",
	"Oswald Veblen",
	"Abraham Adrian Albert",
	"Harry Vandiver",
	"Princeton University",
	"Fritz Noether",
	"Technische Hochschule Breslau",
	"Tomsk",
	"Medvedev Forest massacre",
	"Tumor",
	"Human pelvis",
	"Ovarian cyst",
	"Cantaloupe",
	"Uterus",
	"Circulatory collapse",
	"Pavel Alexandrov",
	"Bryn Mawr College",
	"Abstract algebra",
	"Topology",
	"Noether's theorem",
	"Theoretical physics",
	"Dynamical system",
	"Hermann Weyl",
	"Invariant theory",
	"Paul Gordan",
	"David Hilbert",
	"Ernst Sigismund Fischer",
	"Noether's theorem",
	"Ring (mathematics)",
	"Noncommutative algebra",
	"Linear map",
	"Ideal (ring theory)",
	"Ring (mathematics)",
	"Richard Dedekind",
	"Elimination theory",
	"Algebraic variety",
	"Algebra",
	"Cubic function",
	"Quartic equation",
	"Quintic equation",
	"Root of unity",
	"Regular polygon",
	"Compass and straightedge constructions",
	"Carl Friedrich Gauss",
	"Prime number",
	"Integer factorization",
	"Gaussian integer",
	"�\x89variste Galois",
	"Permutation group",
	"William Rowan Hamilton",
	"Quaternion",
	"Arthur Cayley",
	"Abstract algebra",
	"Group (mathematics)",
	"Ring (mathematics)",
	"Element (mathematics)",
	"Closure (mathematics)",
	"Associativity",
	"Identity element",
	"Inverse element",
	"Commutativity",
	"Associative property",
	"Distributivity",
	"Commutativity",
	"Multiplicative inverse",
	"Division ring",
	"Field (mathematics)",
	"Integer",
	"Addition",
	"Multiplication",
	"Commutativity",
	"Matrix (mathematics)",
	"Quaternion",
	"Fundamental theorem of arithmetic",
	"Prime number",
	"Lasker–Noether theorem",
	"Ideal (ring theory)",
	"Group representation",
	"Vector space",
	"Symmetry",
	"Module (mathematics)",
	"Algebra over a field",
	"Exclusive or",
	"Logical conjunction",
	"Invariant theory",
	"Algebraic invariant theory",
	"Group (mathematics)",
	"Felix Klein",
	"Erlangen program",
	"Geometry",
	"Cross-ratio",
	"Projective geometry",
	"Discriminant",
	"Quadratic form",
	"Euclidean vector",
	"Dot product",
	"Inner product",
	"Linear operator",
	"Matrix (mathematics)",
	"Special linear group",
	"Homogeneous polynomial",
	"Special orthogonal group",
	"Galois theory",
	"Field (mathematics)",
	"Permutation",
	"Degree of a polynomial",
	"Ground field",
	"Real number",
	"Rational number",
	"Integer",
	"Modular arithmetic",
	"Root of a function",
	"Field extension",
	"Imaginary unit",
	"Splitting field",
	"Galois group",
	"Automorphism",
	"Complex conjugation",
	"Permutation",
	"Fundamental theorem of Galois theory",
	"Subgroup",
	"Inverse Galois problem",
	"Noether's problem",
	"Symmetric group",
	"Transcendental extension",
	"Ernst Sigismund Fischer",
	"Richard Swan",
	"Cyclic group",
	"Galois group",
	"Göttingen",
	"General relativity",
	"Gravitation",
	"Albert Einstein",
	"Conservation of energy",
	"Theoretical physics",
	"Noether's theorem",
	"Angular momentum",
	"Conservation of angular momentum",
	"Conservation law (physics)",
	"Momentum",
	"Energy",
	"Theoretical physics",
	"Empty set",
	"Subset",
	"Set (mathematics)",
	"Ascending chain condition",
	"Abstract algebra",
	"Noetherian (disambiguation)",
	"Noetherian ring",
	"Noetherian group",
	"Noetherian module",
	"Module (mathematics)",
	"Noetherian space",
	"Topological space",
	"Spectrum of a ring",
	"Mutatis mutandis",
	"Ring of formal power series",
	"Noetherian induction",
	"Well-founded induction",
	"Mathematical induction",
	"Partially ordered set",
	"Counterexample",
	"Contrapositive",
	"Ring theory",
	"Commutative ring",
	"Ideal (ring theory)",
	"Claude Chevalley",
	"Noetherian ring",
	"Lasker–Noether theorem",
	"Fundamental theorem of arithmetic",
	"Prime number",
	"Dedekind domain",
	"Krull dimension",
	"Integrality",
	"Isomorphism theorem",
	"Natural isomorphism",
	"Artinian module",
	"Elimination theory",
	"Polynomial factorization",
	"Resultant",
	"Linear transform",
	"Determinant",
	"Coprime",
	"Factorial",
	"William Haboush",
	"Haboush's theorem",
	"Noether normalization lemma",
	"Integral domain",
	"Algebraic independence",
	"Integrality",
	"Hermann Weyl",
	"Topology",
	"Connected space",
	"Algebraic topology",
	"Combinatorial topology",
	"Homology theory",
	"Heinz Hopf",
	"Betti group",
	"Euler characteristic",
	"Group theory",
	"Austria",
	"Vienna",
	"Leopold Vietoris",
	"Homology group",
	"Walther Mayer",
	"Hypercomplex number",
	"Group representation",
	"Associative algebra",
	"Module (mathematics)",
	"Ideal (ring theory)",
	"Ring (mathematics)",
	"Ascending chain condition",
	"Emil Artin",
	"Richard Brauer",
	"Helmut Hasse",
	"Central simple algebra",
	"Richard Brauer",
	"Division algebra",
	"Hasse principle",
	"Algebraic number field",
	"Central simple algebra",
	"Skolem–Noether theorem",
	"Brauer–Noether theorem",
	"Bartel Leendert van der Waerden",
	"Jeremy Gray",
	"Pavel Alexandrov",
	"Hermann Weyl",
	"Jean Dieudonné",
	"The New York Times",
	"Albert Einstein",
	"List of things named after Emmy Noether",
	"Timeline of women in science",
	"Mathematisches Forschungsinstitut Oberwolfach",
	"Clark Kimberling",
	"Category:1882 births",
	"Category:1935 deaths",
	"Category:20th-century German inventors",
	"Category:20th-century German mathematicians",
	"Category:20th-century German scientists",
	"Category:20th-century German physicists",
	"Category:20th-century women scientists",
	"Category:20th-century women mathematicians",
	"Category:20th-century German women",
	"Category:Converts to Lutheranism from Judaism",
	"Category:Algebraists",
	"Category:Bryn Mawr College faculty",
	"Category:Institute for Advanced Study visiting scholars",
	"Category:Jewish emigrants from Nazi Germany to the United States",
	"Category:German women mathematicians",
	"Category:German women physicists",
	"Category:Women inventors",
	"Category:Jewish women scientists",
	"Category:Jewish German physicists",
	"Category:Jewish scientists",
	"Category:People from Erlangen",
	"Category:People from the Kingdom of Bavaria",
	"Category:Academic staff of the University of Göttingen",
	"Category:University of Erlangen-Nuremberg alumni",
	"Category:Bavarian emigrants to the United States",
}
